spring:
  datasource:
    url: jdbc:mysql://localhost:8080/newdb
    username: developer
    password: password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
